config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'books#index'do
    root to: 'contents#index'
  end
  resources :books do
    resources :contents do
      resources :comments, only: :create
    end
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :contents, dependent: :destroy
  has_one_attached :image

  with_options presence: true do
    validates :title
    validates :learn
    validates :genre
  end

  def self.search(search)
    if search != ""
      Book.where('text LIKE(?)', "%#{search}%")
    else
      Book.all
    end
  end
  
  def was_attached?
    image.was_attached?
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :content
  belongs_to :user
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :book
  has_many :comments

  with_options presence: true do
    validates :chapter
    validates :write_down
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :comments

  validates :nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :set_book, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show, :seach]

  def index
    @books = Book.includes(:user).order("created_at DESC")
  end

  def new
    @book = Book.new
  end

  def create
    book = Book.create(book_params)
    if book.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to root_path
  end

  def edit
  end

  def update
    book = Book.find(params[:id])
    if book.update(book_params)
      redirect_to book_path
    else
      render :edit
    end
  end

  def show
  end

  def search
    @books = Book.search(params[:keyword])
  end
  
  private

  def book_params
    params.require(:book).permit(:title, :writer, :learn, :genre, :image).merge(user_id: current_user.id)
  end

  def set_book
    @book = Book.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @commnet = Comment.create(comment_params)
    if @comment.save
      redirect_to book_content_path(content.book_id, content.id)
    else
      @book = @comment.book
      @comments = @book.comments
      render "books/[book.id]/show"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, content_id: params[:content_id])
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :set_content, only: [:show, :edit]
  before_action :move_to_index, only: [:edit]

  def index
    @content = Content.new
    @book = Book.find(params[:book_id])
    @contents = @book.contents.includes(:book).order("created_at DESC")
  end

  def new
    @content = Content.new
  end

  def create
    @book = Book.find(params[:book_id])
    contents = @book.contents.new(content_params)
    if contents.save
      redirect_to book_contents_path(@book)
    else
      render :index
    end
  end

  def destroy
    content = Content.find(params[:id])
    content.destroy
    redirect_to action: :index
  end

  def edit
  end

  def update
    content = Content.find(params[:id])
    content.update(content_params)
    if content.update(content_params)
      redirect_to content_path
    else
      @content = Content.find(params[:id])
      render :edit
    end
  end

  #def show
    #@comment = Comment.new
    #@comments - @content.comments.includes(:comment)
  #end

  private

  def content_params
    params.permit(:chapter, :write_down, :wrap_up, :action_plan).merge(book_id: params[:book_id])
  end

  def set_content
    @content = Content.find(params[:id])
  end

  def move_to_index
    unless current_user.id == @content.id
      redirect_to action: :index
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @books = @user.books
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<div class="card">
  <%= link_to image_tag(book.image, class: :card__img), book_path(book.id) %>
  <div class="card__body">
    <%= link_to book.title, book_path(book.id), class: :card__title %>
    <%= link_to book.writer, book_path(book.id), class: :card__title %>
    <%= link_to "by #{book.user.nickname}",  user_path(book.user), class: :card__user %>
  </div>
</div>

app/views/books/_form.html.erb
<%= form_with model: @book, local: true do |f| %>
  <div class="field">
    <%= f.label :title, "本のタイトル" %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :writer, "本の著者" %><br />
    <%= f.text_field :writer %>
  </div>

  <div class="field">
    <%= f.label :learn, "本から学びたいこと" %><br />
    <%= f.text_area :learn, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :genre, "本の種類" %><br />
    <%= f.text_area :genre, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :image, "本の画像" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
  <%= render partial: "form", locals: { book: @book } %>
  </div>
</div>

app/views/books/index.html.erb
<main class="main">
  <div class="inner">
    <%#= form_with(url: search_books_path, local: true, method: :get, class: "search-form") do |form| %>
      <%#= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
      <%#= form.submit "検索", class: "search-btn" %>
    <%# end %>
    <%# ログインしているときは以下を表示する %>
    <% if user_signed_in? %>
    <% end %>
    <%# // ログインしているときは上記を表示する %>
    <div class="card__wrapper">
      <%# 投稿機能実装後、部分テンプレートで本の投稿一覧を表示する %>
      <%= render partial: 'book', collection: @books %>
    </div>
  </div>
</main>

app/views/books/new.html.erb
<div class="content row">
  <div class="container">
    <h3>投稿する</h3>
      <%= render partial: "form", locals: { book: @book } %>
  </div>
</div>

app/views/books/search.html.erb
<%= form_with(url: search_books_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="content row">
  <% @books.each do |book| %>
    <%= render partial: "book", locals: { book: @book } %>
  <% end %>
</div>

app/views/books/show.html.erb
<main class="main">
  <div class="inner">
    <div class="book__wrapper">
      <p class="book__hedding">
        <%= @book.title%>
      </p>
      <div class="book__body">
        <div class="book__detail">
          <p class="detail__message">著者</p>
            <%= @book.writer %>
          </p>
        </div>
      </div>
      <%# 本の投稿者とログインしているユーザーが同じであれば以下を表示する %>
      <% if user_signed_in? && current_user.id == @book.user_id%>
        <div class="book__manage">
          <%= link_to "編集する", edit_book_path(@book.id), class: :book__btn %>
          <%= link_to "削除する", book_path(@book.id), method: :delete, class: :book__btn %>
        </div>
      <% end %>
      <%# // 本の投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <div class="book__image">
        <%= image_tag @book.image %>
        <p class="detail__message">本から学びたいこと</p>
          <%= @book.learn %>
        </p>
      <% if user_signed_in? && current_user.id %>
        <div class="book__manage">
          <%= link_to "内容", book_contents_path(@book.id), class: :book__btn %>
        </div>
      <% end %>
      </div>
      <%= link_to "by#{@book.user.nickname} ", user_path(@book.user.id), class: :book__user %>
    </div>
  </div>
</main>

app/views/contents/_content.html.erb
<div class="content">
  <div class="card__body">
    <%=link_to content.chapter, book_content_path(content.book_id, content.id), class: :card__title  %>
  </div>
</div>

app/views/contents/_form.html.erb
<%= form_with url:book_contents_path, method: :post, local: true do |f| %>
  <div class="field">
    <%= f.label :chapter, "題目" %><br />
    <%= f.text_field :chapter ,class: :form__text%>
  </div>

  <div class="field">
    <%= f.label :write_down, "本の書き抜き" %><br />
    <%= f.text_area :write_down , class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :wrap_up, "要約" %><br />
    <%= f.text_area :wrap_up, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :action_plan, "コメント・アクションプラン" %><br />
    <%= f.text_area :action_plan, class: :form__text %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
  <%= render partial: "form", locals: { content: @contents } %>
  </div>
</div>

app/views/contents/index.html.erb
<main class="main">
  <div class="book__inner">
    <%= "内容一覧" %>
    <div class="content__inner">
      <%# ユーザーがログインしていてかつ投稿者と同じ場合は以下を表示する %>
      <% if user_signed_in? && current_user.id == @book.user.id %>
        <div class="greeting">
          <%= link_to "内容の新規投稿", new_book_content_path, class: :greeting__link%>
        </div>
      <% end %>
      <%# // ログインしているときは上記を表示する %>
      <div class="content__wrapper">
        <%# 投稿機能実装後、部分テンプレートで内容の一覧を表示する %>
        <%= render partial: 'content', collection: @contents %>
      </div>
    </div>
  </div>
</main>

app/views/contents/new.html.erb
<div class="content row">
  <div class="container">
    <h3>内容を投稿する</h3>
      <%= render partial: "form", locals: { content: @content } %>
  </div>
</div>

app/views/contents/show.html.erb
<main class="main">
  <div class="book__wrapper">
    <div class="book__body">
    <%# 本の投稿者とログインしているユーザーが同じであれば以下を表示する %>
    <% if user_signed_in? && current_user.id #== @contents_id%>
      <div class="book__manage">
        <%= link_to "編集する", edit_book_content_path(@content.id), class: :book__btn %>
      </div>
    <% end %>
    <%# 本の投稿者とログインしているユーザーが同じであれば以下を表示する %>
      <div class="contents__detail">
        <div class="book__inner">
          <p class="detail__message">題目</p>
            <div class="content__inner">
              <p class="detail__message">
                <%= @content.chapter %>
              </p>
            </div>
        </div>
      </div>
      <div class="contents__detail">
        <div class="book__inner">
          <p class="detail__message">書き抜き</p>
            <div class="content__inner">
              <p class="detail__message">
                <%= @content.write_down %>
              </p>
            </div>
        </div>
      </div>
      <div class="contents__detail">
        <div class="book__inner">
          <p class="detail__message">要約</p>
            <div class="content__inner">
              <p class="detail__message">
                <%= @content.wrap_up %>
              </p>
            </div>
          </div>
        </div>
      <div class="contents__detail">
        <div class="book__inner">
          <p class="detail__message">コメント・アクションプラン</p>
          <div class="content__inner">
            <p class="detail__message">
              <%= @content.action_plan %>
            </p>
          </div>
        </div>
      </div>
    <%# 本の投稿者とログインしているユーザーが同じであれば以下を表示する %>
    <% if user_signed_in? && current_user.id #== @contents_id%>
      <div class="book__manage">
        <%= link_to "削除する", book_content_path(@content.id), method: :delete, class: :book__btn %>
      </div>
    <% end %>
    <%# 本の投稿者とログインしているユーザーが同じであれば以下を表示する %>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ReadingBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
     <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
          <%= link_to "Reading Books", root_path %>
          </div>
          <%# ログインしているときの表示 %>
          <% if user_signed_in? %>
            <div class="greeting">
              <%= "こんにちは" %>
              <%= link_to "#{current_user.nickname}さん", user_path(current_user.id), class: :greeting__link%>
            </div>
            <div class="nav__right" %>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to "New Book", new_book_path, class: :nav__btn %>
            </div>
          <%# // ログインしているときの表示 %>
          <% else %>
          <%# ログインしていないときの表示 %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
          <%# // ログインしていないときの表示 %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="Copyright"> ReadingBook All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.nickname}さんの情報"%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.nickname %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.nickname}さんの読書履歴"%>
      </h2>
      <div class="user__card">
        <%# 部分テンプレートでそのユーザーが投稿したプロトタイプ投稿一覧を表示する %>
        <%= render partial: 'books/book', collection: @books %>
      </div>
    </div>
  </div>
</div>